fix: remplace cv url by cv binary
Riminder/hrflow-connectors pull request #220
Opened 2024-02-06 18:19 UTC by Abdellahitech

2024-02-08 13:45 UTC, the-forest-tree requested changes
Le pattern `except Exception` est à enlever partout. Est ce que je t'ai pas déjà expliquer que c'est une pratique dangereuse ?

2024-02-08 13:45 UTC, the-forest-tree commented on src/hrflow_connectors/connectors/jobology/warehouse.py
> +    except Exception as e:
Non ca c'est trop `excep Exception` ca va tout catcher. Ca veut dire si par exemple dans ton code a un moment tu fais une erreur du genre 
```python
try: 
    binary_data = base64.b64decodeX(cv_base64) <==== le X à la fin de ba64decode 
```
Tu vas rien voir. Soubhana Lah. Tu trouves ca normal ? 

Tu vas raiser en dessous Base64DecodeError comme si c'est un problème dans la data alors que en fait c'est une erreur. La méthode `b64decodeX` n'existe pas il faut enlever le `X` 


Le message c'est que faut quasiment jamais faire `except Exception` c'est trop dangereux. Donc la soit tu vas chercher les erreur suceptible d'être raisé du genre si tu fais `json.loads(SOME_USER_DATA_THAT_MIGHT_BE_MALFORMATED)` tu peux faire except JSONDecodeError ici c'est justifié. 

Mais `except Exception` non c'est trop

2024-02-08 13:45 UTC, the-forest-tree commented on src/hrflow_connectors/connectors/jobology/warehouse.py
> +    except Exception as e:
Même commentaire par rapport à except Exception 
Tu remplaces ca par l'erreur qui peut être raisé en circonstance normale

2024-02-10 14:41 UTC, Abdellahitech commented on src/hrflow_connectors/connectors/jobology/warehouse.py
> +    except Exception as e:
ok j'ai enlevé le catch des erreurs. en cherchant j'ai trouvé qu'il y a une erreur possible que le len soit pas divisible par 4 donc à ajouter des 4. c'est seulement l'erreur que j'ai catché

2024-02-12 09:31 UTC, merged