feat: update the manifest generation process
Riminder/hrflow-connectors pull request #268
Opened 2024-08-05 09:27 UTC by nedhirouebnou

Add Jsonmap mappings to manifest.json & automattically add 'mappings/format' folder in every connector's directory

2024-08-05 09:47 UTC, the-forest-tree requested changes
Merci pour le travail 

Ca nécessite encore un peu de travail incha Lah

2024-08-05 09:47 UTC, the-forest-tree commented on tests/core/test_documentation.py
> +
Rajoute ici `format_mappings_directory.exists() is False`

2024-08-05 09:47 UTC, the-forest-tree commented on tests/core/test_manifest.py
> +    # Ensure the format_mappings_directory exists
Enlève ce commentaire stp

2024-08-05 09:47 UTC, the-forest-tree commented on tests/core/test_manifest.py
> +    # Ensure the format_mappings_directory exists but not the jsonmap_file
A enlever

2024-08-05 09:47 UTC, the-forest-tree commented on src/hrflow_connectors/core/connector.py
> +            "Starting to read from warehouse={} with mode={} read_from={} parameters={}".format(
Le commentaire est valable pour ces lignes et aussi les trois blocs qui suivent. Pourquoi tu as ce changement ? 

Aussi une chose importante c'est que quand tu fais une PR une bonne chose à faire c'est de la lire toi même. 
Quand tu l'as lis tu regardes c'est quoi les changements qui sont lié à ta PR et tu te poses la question est ce que c'est bien valide ou pas ? 

Parce que ici la question c'est pourquoi ces changements ? 

Check ton setup ou la config de VSCode parce que la j'ai relancé `black` après un fresh install et ca me donne pas ces changements

2024-08-05 09:47 UTC, the-forest-tree commented on src/hrflow_connectors/core/documentation.py
> +
En fait ca ne fait pas tout le travail. Parce que la question qui se pose mnt c'est ou ils sont tous les folders `mappings` ? 

Je les vois pas dans la PR. Pourquoi ils apparaissent pas ?
Lis plus en détail le code pour les folders `notebooks` tu vas voir qu'il te manque de la logique. Quand tu la rajoute incha Lah pense aussi à mettre à jour les tests

2024-08-05 09:50 UTC, the-forest-tree commented
Aussi d'un point de vue flow. Tu ne demandes une review qu'après avoir fait les deux choses suivantes : 
- Tu relis la PR en allant dans la partie changes. Tu vérifies que y'a pas de changement non voulu ou de truc a priori important qui manquent (comme en l'occurence ici les folder mappings) 
- `core-test` doit passer autrement c'est pas encore prêt à être review

2024-08-05 11:48 UTC, nedhirouebnou commented on src/hrflow_connectors/core/connector.py
> +            "Starting to read from warehouse={} with mode={} read_from={} parameters={}".format(
C'est en fait lié à ma configuration VsCode qui fait le formatage lors de la sauvegarde 'formatOnSave' mais j'ai défini Black comme formateur par défaut, donc je ne sais pas pourquoi il formate différemment de "make style". Je vais faire attention à bien lancer "make style" à chaque fois avant de push mes changements.

2024-08-05 13:35 UTC, the-forest-tree commented on src/hrflow_connectors/core/connector.py
> +            "Starting to read from warehouse={} with mode={} read_from={} parameters={}".format(
En fait c'est bien d'avoir `formatOnSave` sur VsCode moi aussi j'ai ca. Mais le truc c'est juste de faire en sorte que l'Extension Black coté VsCode utilise le `black` installé dans ton env poetry avec la config dans `pyproject.toml`  

Une fois que tu as réglé ca coté VsCode ca devrait être bon inshaa Lah

2024-08-05 13:38 UTC, the-forest-tree commented on src/hrflow_connectors/core/connector.py
> +            "Starting to read from warehouse={} with mode={} read_from={} parameters={}".format(
Voila un example de ce que j'ai dans `.vscode/settings.json` pour que ca marche. C'est possible que les keys ait changé d'une version à une autre mais l'idée devrait être la même 
```json
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "errorLens.messageTemplate": "[$source][$code] $message",
  "editor.formatOnSave": true,
  "flake8.args": ["--config", "./.flake8"],
  "json.validate.enable": true,
  "[python]": {
    "editor.defaultFormatter": "ms-python.black-formatter",
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
      "source.organizeImports": "explicit"
    }
  },
  "[markdown]": {
    "editor.formatOnSave": false
  },
  "black-formatter.args": ["--config", "pyproject.toml"],
  "black-formatter.path": ["black"],
  "flake8.path": ["flake8"]
```

2024-08-19 14:34 UTC, the-forest-tree requested changes
Merci Nedhir je trouve que c'est bien cette nouvelle version. 

Il manque une dernière subtilité qui est apparu mnt qu'on a les gitkeep. C'est expliqué dans le commentaire sur `IGNORED_PATHS` dans `tests/core/test_documentation.py`

2024-08-19 14:34 UTC, the-forest-tree commented on src/hrflow_connectors/core/documentation.py
Allahouma barik c'est bien ton refactor ici

2024-08-19 14:34 UTC, the-forest-tree commented on tests/core/test_documentation.py
> +    "notebooks/{}".format(KEEP_EMPTY_FOLDER),
Alors en fait la dernière partie incha Lah qui manque à cette PR c'est mettre à jour cette partie à la fois dans les tests et dans core. 

Comme tu peux le voir dans ton change. Quand tu as fais `make manifest` a priori la date de Last Updated At de tous les connecteur à été mis à jour. Alors que dans ta PR tu as touché à aucun connecteur ? 

Si je me trompe pas c'est parce que pour chaque connecteur `make docs` a detecter le rajout de `.gitkeep` pour chaque connecteur. Et ca dit ok du coup doit y avoir une modification donc je met à jour Last Updated At dans README sauf que ici c'est clairement un _faux positif_. Parce que rajouter un fichier `.gitkeep` vide ca a aucun impact sur le code, les features etc.. d'un connecteur. 

Pour gérer ces cas dans le code qui s'occupe de mettre à jour Last Updated At dans core il y'au ne logique de IGNORED_PATHS qui dit. Si tu vois un changement dans ces path ne répercute pas dans le README. 

Du coup ce qui manque c'est régler ce dernier point baraka Lah fik

2024-08-22 10:06 UTC, nedhirouebnou commented on src/hrflow_connectors/core/documentation.py
Merci beaucoup Allah ybark fik

2024-08-22 10:06 UTC, nedhirouebnou commented on tests/core/test_documentation.py
> +    "notebooks/{}".format(KEEP_EMPTY_FOLDER),
J'ai ajouté le chemin dans la variable `IGNORED_PATHS` comme suit :
```
IGNORED_PATHS = [
    "notebooks/{}".format(KEEP_EMPTY_FOLDER),
    "mappings/format/{}".format(KEEP_EMPTY_FOLDER),
    "README.md",
    "test-config.yaml",
    "logo.png",
    "docs/pull_action.md",
]
```
Les dates dans le fichier README.md continuent toutefois d'être mises à jour. Il semble que ce fichier ne soit pas encore ignoré, car le test `pytest tests/core/test_documentation.py::test_ignored_path_are_not_taken_into_account_for_main_readme_updated_at` échoue après cette modification.

Y a-t-il une autre modification à apporter ou quelque chose que j'ai oublié ?

2024-08-22 10:09 UTC, the-forest-tree commented on tests/core/test_documentation.py
> +    "notebooks/{}".format(KEEP_EMPTY_FOLDER),
Tu as rajouter ca juste dans tests ou aussi fait le travail necessaire coté core ?

2024-08-22 11:20 UTC, nedhirouebnou commented on tests/core/test_documentation.py
> +    "notebooks/{}".format(KEEP_EMPTY_FOLDER),
Tout est réglé maintenant et j'ai remis le README.md dans son état initial.

2024-08-22 11:31 UTC, the-forest-tree commented on src/hrflow_connectors/core/documentation.py
> +GIT_UPDATE_EXCLUDE_PATTERN = r"(notebooks/\.gitkeep|mappings/format/\.gitkeep|README\.md|test\-config\.yaml|logo\.png|docs/pull_action\.md)"
C'est bon pour la partie rajouter `mappings/format/.gitkeep` mais il y'a aussi le changement `docs/` qui devient `docs/pull_actions\.md` 

Est ce que c'est bien un changement que toi tu as rajouter ? Parce que c'est surprenant ?

2024-08-22 11:44 UTC, nedhirouebnou commented on src/hrflow_connectors/core/documentation.py
> +GIT_UPDATE_EXCLUDE_PATTERN = r"(notebooks/\.gitkeep|mappings/format/\.gitkeep|README\.md|test\-config\.yaml|logo\.png|docs/pull_action\.md)"
Ah c'est une erreur de ma part, c'est fixé

2024-08-22 11:45 UTC, the-forest-tree commented on src/hrflow_connectors/core/documentation.py
> +GIT_UPDATE_EXCLUDE_PATTERN = r"(notebooks/\.gitkeep|mappings/format/\.gitkeep|README\.md|test\-config\.yaml|logo\.png|docs/pull_action\.md)"
Ok ca marche

2024-08-22 11:48 UTC, the-forest-tree approved these changes
Ok merci pour le travail ca me semble bon mnt

2024-08-22 11:49 UTC, merged