feature/connector-hubspot: Hubspot Connector v2.0
Riminder/hrflow-connectors pull request #98
Opened 2022-11-10 14:19 UTC by nedhirouebnou

2022-12-22 14:26 UTC, the-forest-tree requested changes
Encore une fois bon travail @nedhirouebnou Allahouma barik. 

Quelques changements mineurs.

2022-12-22 14:26 UTC, the-forest-tree commented on src/hrflow_connectors/connectors/hubspot/warehouse.py
> +    propertiesWithHistory: List[Properties] = Field(
snake case `properties_with_history`

2022-12-22 14:26 UTC, the-forest-tree commented on src/hrflow_connectors/connectors/hubspot/warehouse.py
> +baseUrl = "https://api.hubapi.com/crm/v3"
`BASE_URL` pour être cohérent avec le reste de nos connecteurs. 

Si la PR venait d'un contributeur externe à la boite je n'aurais pas fait de remarque. 
Parce que forcement dés que tu veux avoir des contributions externes tu vas forcement céder un peu de cohérence et surtout tu peux pas reprocher ce que tu n'a pas explicitement partagé comme étant un standard.

Mais bon vu que pour l'instant on est les contributeur autant rester cohérent.

2022-12-22 14:26 UTC, the-forest-tree commented on src/hrflow_connectors/connectors/hubspot/warehouse.py
> +    displayOrder: int
`display_order`

2022-12-22 14:26 UTC, the-forest-tree commented on src/hrflow_connectors/connectors/hubspot/warehouse.py
> +    displayOrder: int
snake case et partout ailleurs dans le fichier

2022-12-22 14:26 UTC, the-forest-tree commented on src/hrflow_connectors/connectors/hubspot/warehouse.py
> +    url = f"{baseUrl}/objects/contacts"
Pour l'instant dans le project c'est partout du `"...".format()`. 
Clairement _f-strings_ c'est bien mais l'idée c'est soit de rester sur `.format()` soit tout passer en `f-string` mais pas l'un et l'autre pour préserver la cohérence. 

Si tu es motivé tu peux tout passer en _f-string_

2022-12-22 14:26 UTC, the-forest-tree commented on src/hrflow_connectors/connectors/hubspot/warehouse.py
> +    contacts_endpoint = f"{baseUrl}/objects/contacts"
`format()`

2022-12-22 14:26 UTC, the-forest-tree commented on src/hrflow_connectors/connectors/hubspot/warehouse.py
> +        )
Utilises plutôt `json` à la place de `data` ca te fait aussi la ligne `"Content-Type"` en moins à écrire et plus besoin de `json.dumps(profile)` plus haut non plus.

2022-12-22 14:26 UTC, the-forest-tree commented on src/hrflow_connectors/connectors/hubspot/warehouse.py
> +    # read=WarehouseReadAction(parameters=ReadProfilesParameters, function=read),
Ici il faut choisir. Soit tu ship le `read` soit tu enlèves cette ligne et tout le code lié.

2022-12-22 14:26 UTC, the-forest-tree commented on src/hrflow_connectors/connectors/hubspot/test-config.yaml
> +warehouse: {}
Rajoute un test de warehouse stp.

2022-12-22 14:26 UTC, the-forest-tree commented on src/hrflow_connectors/connectors/hubspot/connector.py
> +        # languages="",
A supprimer si non utilisé.

2022-12-26 09:44 UTC, nedhirouebnou commented on src/hrflow_connectors/connectors/hubspot/warehouse.py
> +    propertiesWithHistory: List[Properties] = Field(
Ce sont les paramètres utilisés par l'api Hubspot, j'ai donc gardé la même nomenclature que dans leur doc.

2023-01-12 15:06 UTC, merged