feature/connector-recruitee: Recruitee Connector v2.0
Riminder/hrflow-connectors pull request #99
Opened 2022-11-10 14:56 UTC by nedhirouebnou

2022-12-22 13:59 UTC, the-forest-tree requested changes
Allahouma barik ! 

Merci pour le travail de qualité @nedhirouebnou.  

Seulement quelques remarques mineures. 

Le truc important c'est de bien rebaser sur la version la plus à jour de master pour corriger le problème dans le doc avant de rajouter les changements demandés.

2022-12-22 13:59 UTC, the-forest-tree commented on src/hrflow_connectors/connectors/recruitee/warehouse.py
> +    API_Token: str = Field(
Est ce qu'il y'a raison particulière de ne pas mettre le paramètre en snake case ? `api_token`

2022-12-22 13:59 UTC, the-forest-tree commented on src/hrflow_connectors/connectors/recruitee/warehouse.py
> +    offers: t.List[int] = Field(
Appelle plutôt ca `offer_ids` c'est plus explicite.

2022-12-22 13:59 UTC, the-forest-tree commented on src/hrflow_connectors/connectors/recruitee/warehouse.py
> +        raise Exception(
Rajoute ici du logging en mode erreur comme tu l'as fais à d'autre endroits

2022-12-22 13:59 UTC, the-forest-tree commented on src/hrflow_connectors/connectors/recruitee/warehouse.py
> +            "Failed to pull candidates list from Recruitee."
Je pense que cette ligne est en trop.

2022-12-22 13:59 UTC, the-forest-tree commented on src/hrflow_connectors/connectors/recruitee/docs/pull_jobs.md
> +        view_mode=brief,
Ici il y'a un bug qui ne vient pas de ton code mais plutôt de la partie core documentation. Il faudrait que ca soit plutôt `"brief"`. 

Pour ton information une [PR](https://github.com/Riminder/hrflow-connectors/pull/101 ) pour régler ce problème a été mergé. 

Du coup il faudra avant de faire les modifications rebaser ta branche sur la dérniere version de master pour que le problème soit corrigé incha Lah.

2022-12-22 13:59 UTC, the-forest-tree commented on src/hrflow_connectors/connectors/recruitee/connector.py
> +    cv_url = next(filter(lambda x: x.get("type") == "resume", attachments))[
Tu as aussi cette variante sans le filter et la lambda. Tu en penses quoi ?
```python
cv_url = next((attachment for attachment in attachments if attachment.get("type") == "resume"))["public_url"]
```
Tu es pas obligé de changer. C'est plus pour discuter.

2022-12-22 13:59 UTC, the-forest-tree commented on src/hrflow_connectors/connectors/recruitee/connector.py
> +        sections=get_sections(recruitee_job),
Tu peux te passer de `get_sections` vu que ici c'est une liste avec un seul element. 
Simplement dans la première ligne de `format_job` défini `sections = [dict(name=....)]` et rajoute le ici. 

Il faut un minimum de complexité pour justifier l'utilisation d'une fonction.

2022-12-22 13:59 UTC, the-forest-tree commented on src/hrflow_connectors/connectors/recruitee/test-config.yaml
> +warehouse: {}
Rajoute au moins un test de warehouse qui est censé marché comme [ici](https://github.com/Riminder/hrflow-connectors/blob/master/src/hrflow_connectors/connectors/smartrecruiters/test-config.yaml#L1)

2022-12-23 10:50 UTC, nedhirouebnou commented on src/hrflow_connectors/connectors/recruitee/connector.py
> +    cv_url = next(filter(lambda x: x.get("type") == "resume", attachments))[
Je pense que ta façon de filtrer en utilisant une liste de compréhension exprime l'intention plus clairement et est donc plus facile à comprendre, je vais donc la choisir.

2023-01-12 14:14 UTC, merged